### PR TITLE
Update ruby to 2.3.7

### PR DESCRIPTION
**Pull request by stuaxo**

### CODE REVIEW

**Comment by stuaxo** [comment]
This is the least scary patch to peoplefinder.

**Comment by reupen** [comment]
@stuaxo Will need to update the build pack in manifest.yml as well. 

(Probably want v1.7.18: https://github.com/cloudfoundry/ruby-buildpack/releases)

**Comment by stuaxo** [comment]
I had a feeling something was missing.

**Comment by stuaxo** [comment]
Randomly failing test is annoying :/

**Pull request merged**
