### PR TITLE
Remove 1 victoria street, add 50 victoria street

### PR DESCRIPTION
**Pull request by stuaxo**
Ready to merge - removing 1 victoria street from any people is now achieved in a merge.

### CODE REVIEW

**Comment by stuaxo** [comment]
OK, this is clearly dying on http://peoplefinder-dev.cloudapps.digital/ can we revert it there ?

**Comment by stuaxo** [comment]
This seems to be working on  http://peoplefinder-dev.cloudapps.digital/  - I can set my address to Windsor House and save it and reload it at least.

**Comment by agiamas** [comment]
@stuaxo if you are sure that existing entries won't get affected, feel free to merge. I'm not, as I dont know if you have auto deploy or not :)

**Comment by stuaxo** [comment]
A test would be a good idea.... though being able to run them locally and have them pass would be a prerequisite.

To more closely match travis, I installed ruby in an Ubuntu 14.04 vm, using rvm.

```bundle exec rake``` gets exactly the same error as on my real laptop - pretty sure I'm missing something really obvious, but going to have to give up on this if I can't fix it.

```
Coverage report Rcov style generated for RSpec to /home/stu/peoplefinder/coverage/rcov
/home/stu/peoplefinder/spec/support/pages/edit_profile.rb:5:in `<module:Pages>': uninitialized constant Pages::Base (NameError)
	from /home/stu/peoplefinder/spec/support/pages/edit_profile.rb:4:in `<top (required)>'
	from /home/stu/peoplefinder/spec/rails_helper.rb:45:in `block in <top (required)>'
	from /home/stu/peoplefinder/spec/rails_helper.rb:45:in `each'
	from /home/stu/peoplefinder/spec/rails_helper.rb:45:in `<top (required)>'
	from /home/stu/peoplefinder/spec/config/initializers/delayed_job_spec.rb:1:in `require'
	from /home/stu/peoplefinder/spec/config/initializers/delayed_job_spec.rb:1:in `<top (required)>'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/stu/.rvm/gems/ruby-2.3.5/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
```

**Comment by stuaxo** [comment]
OK, now all the tests are passing, I'm going to add the missing parts to this before merging.

**Comment by stuaxo** [comment]
Holy fsck I can actually write queries in ActiveRecord now - so I can finally implement removing this fscking building.  fuck.

**Comment by stuaxo** [comment]
Dear travis ... hurry up.

**Pull request merged**
